language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot2-webservice *
  - mkdir -p deploy
  - mv springboot2-webservice.zip deploy/springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: woodee-springboot-build
    #region: ap-northeast-2
    region: us-east-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: woodee-springboot-build # S3 버킷
    key: springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: springboot2-webservice #CodeDeploy
    deployment_group: springboot2-webservice-group #CodeDeploy
    #region: ap-northeast-2
    region: us-east-2
    wait-until-deployed: true


#
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - woodeekim@gmail.com

#TravisCI->S3->CodeDeploy->EC2 시 region 설정 중요하다.
#특히 EC2 접속 후 aws s3 cp s3://aws-codedeploy-us-east-2/latest/install . --region us-east-2 다운 받을 때도 마찬가지다.